-- PA999_DEMO 데이터베이스 생성
IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'PA999_DEMO')
BEGIN
    CREATE DATABASE PA999_DEMO COLLATE Korean_Wansung_CI_AS;
    PRINT 'PA999_DEMO 데이터베이스 생성 완료';
END
ELSE
    PRINT 'PA999_DEMO 이미 존재';
