//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     이 파일을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Bizentro.App.UI.PP.CB990M1_CKO087
{
    using System;
    using System.Data;
    using System.Runtime.Serialization;
    using System.ComponentModel;

    /// <summary>
    /// dsInput — 저장용 TVP 입력 DataSet
    ///   테이블: I_DATA (UTP_CB990M1_CKO087 와 1:1 대응, 6컬럼)
    ///   컬럼: CUD_CHAR, ROW_NUM, LOG_SEQ, PERF_SCORE, DEV_FEEDBACK, EXT1_CD
    /// </summary>
    [Serializable()]
    [DesignerCategoryAttribute("code")]
    public partial class dsInput : global::System.Data.DataSet
    {
        private I_DATADataTable tableI_DATA;

        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        public I_DATADataTable I_DATA
        {
            get { return this.tableI_DATA; }
        }

        public dsInput()
        {
            this.InitClass();
        }

        protected dsInput(SerializationInfo info, StreamingContext context) : base(info, context) { }

        private void InitClass()
        {
            this.DataSetName = "dsInput";
            this.Prefix      = "";
            this.Namespace   = "http://tempuri.org/dsInput.xsd";
            this.tableI_DATA = new I_DATADataTable();
            base.Tables.Add(this.tableI_DATA);
        }

        // GetTypedDataSetSchema 제거 (XmlSchemaProvider 미사용)

        // ====================================================================
        // I_DATADataTable
        // ====================================================================
        [Serializable()]
        [DesignerCategoryAttribute("code")]
        public partial class I_DATADataTable : TypedTableBase<I_DATARow>
        {
            private DataColumn columnCUD_CHAR;
            private DataColumn columnROW_NUM;
            private DataColumn columnLOG_SEQ;
            private DataColumn columnPERF_SCORE;
            private DataColumn columnDEV_FEEDBACK;
            private DataColumn columnEXT1_CD;

            internal I_DATADataTable()
            {
                this.TableName = "I_DATA";
                this.InitClass();
            }

            public DataColumn CUD_CHARColumn    { get { return this.columnCUD_CHAR; } }
            public DataColumn ROW_NUMColumn     { get { return this.columnROW_NUM; } }
            public DataColumn LOG_SEQColumn     { get { return this.columnLOG_SEQ; } }
            public DataColumn PERF_SCOREColumn  { get { return this.columnPERF_SCORE; } }
            public DataColumn DEV_FEEDBACKColumn{ get { return this.columnDEV_FEEDBACK; } }
            public DataColumn EXT1_CDColumn     { get { return this.columnEXT1_CD; } }

            public int Count { get { return this.Rows.Count; } }

            public I_DATARow this[int index] { get { return (I_DATARow)this.Rows[index]; } }

            private void InitClass()
            {
                this.columnCUD_CHAR     = new DataColumn("CUD_CHAR",     typeof(string), null, MappingType.Element);
                this.columnROW_NUM      = new DataColumn("ROW_NUM",      typeof(int),    null, MappingType.Element);
                this.columnLOG_SEQ      = new DataColumn("LOG_SEQ",      typeof(long),   null, MappingType.Element);
                this.columnPERF_SCORE   = new DataColumn("PERF_SCORE",   typeof(int),    null, MappingType.Element);
                this.columnDEV_FEEDBACK = new DataColumn("DEV_FEEDBACK", typeof(string), null, MappingType.Element);
                this.columnEXT1_CD      = new DataColumn("EXT1_CD",      typeof(string), null, MappingType.Element);

                base.Columns.Add(this.columnCUD_CHAR);
                base.Columns.Add(this.columnROW_NUM);
                base.Columns.Add(this.columnLOG_SEQ);
                base.Columns.Add(this.columnPERF_SCORE);
                base.Columns.Add(this.columnDEV_FEEDBACK);
                base.Columns.Add(this.columnEXT1_CD);
            }

            public I_DATARow AddI_DATARow(string CUD_CHAR, int ROW_NUM, long LOG_SEQ, int PERF_SCORE, string DEV_FEEDBACK, string EXT1_CD = null)
            {
                I_DATARow row = (I_DATARow)this.NewRow();
                if (CUD_CHAR     != null) row[this.columnCUD_CHAR]     = CUD_CHAR;
                if (ROW_NUM      != 0)   row[this.columnROW_NUM]      = ROW_NUM;
                if (LOG_SEQ      != 0)   row[this.columnLOG_SEQ]      = LOG_SEQ;
                if (PERF_SCORE   != 0)   row[this.columnPERF_SCORE]   = PERF_SCORE;
                if (DEV_FEEDBACK != null) row[this.columnDEV_FEEDBACK] = DEV_FEEDBACK;
                // EXT1_CD: 현재 미사용, null 허용 (UTP 6번째 컬럼 맞춤용)
                this.Rows.Add(row);
                return row;
            }

            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) { return new I_DATARow(builder); }
            protected override Type    GetRowType()    { return typeof(I_DATARow); }
        }

        // ====================================================================
        // I_DATARow
        // ====================================================================
        public partial class I_DATARow : DataRow
        {
            private I_DATADataTable tableI_DATA;

            internal I_DATARow(DataRowBuilder rb) : base(rb)
            {
                this.tableI_DATA = (I_DATADataTable)this.Table;
            }

            public string CUD_CHAR
            {
                get { return this.IsNull(this.tableI_DATA.CUD_CHARColumn) ? string.Empty : (string)this[this.tableI_DATA.CUD_CHARColumn]; }
                set { this[this.tableI_DATA.CUD_CHARColumn] = value; }
            }
            public int ROW_NUM
            {
                get { return this.IsNull(this.tableI_DATA.ROW_NUMColumn) ? 0 : (int)this[this.tableI_DATA.ROW_NUMColumn]; }
                set { this[this.tableI_DATA.ROW_NUMColumn] = value; }
            }
            public long LOG_SEQ
            {
                get { return this.IsNull(this.tableI_DATA.LOG_SEQColumn) ? 0L : (long)this[this.tableI_DATA.LOG_SEQColumn]; }
                set { this[this.tableI_DATA.LOG_SEQColumn] = value; }
            }
            public int PERF_SCORE
            {
                get { return this.IsNull(this.tableI_DATA.PERF_SCOREColumn) ? 0 : (int)this[this.tableI_DATA.PERF_SCOREColumn]; }
                set { this[this.tableI_DATA.PERF_SCOREColumn] = value; }
            }
            public string DEV_FEEDBACK
            {
                get { return this.IsNull(this.tableI_DATA.DEV_FEEDBACKColumn) ? string.Empty : (string)this[this.tableI_DATA.DEV_FEEDBACKColumn]; }
                set { this[this.tableI_DATA.DEV_FEEDBACKColumn] = value; }
            }
            public string EXT1_CD
            {
                get { return this.IsNull(this.tableI_DATA.EXT1_CDColumn) ? string.Empty : (string)this[this.tableI_DATA.EXT1_CDColumn]; }
                set { this[this.tableI_DATA.EXT1_CDColumn] = value; }
            }
        }

        public delegate void I_DATARowChangeEventHandler(object sender, I_DATARowChangeEvent e);
        public class I_DATARowChangeEvent : EventArgs
        {
            private I_DATARow eventRow;
            private DataRowAction eventAction;
            public I_DATARowChangeEvent(I_DATARow row, DataRowAction action) { this.eventRow = row; this.eventAction = action; }
            public I_DATARow Row    { get { return this.eventRow; } }
            public DataRowAction Action { get { return this.eventAction; } }
        }
    }
}

#pragma warning restore 1591
