//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     이 파일을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Bizentro.App.UI.PP.CB990M1_CKO087
{
    using System;
    using System.Data;
    using System.Runtime.Serialization;
    using System.ComponentModel;

    /// <summary>
    /// dsWorking — 그리드 표시용 조회 결과 DataSet
    ///   테이블: E_DATA (CB_CB990Q1_CKO087 결과셋과 1:1 대응)
    ///   편집 가능 컬럼: PERF_SCORE, DEV_FEEDBACK
    ///   읽기 전용 컬럼: 나머지 전체
    ///
    ///   실제 PA999_CHAT_LOG 컬럼 기준:
    ///     CREATED_DT   (구 INSRT_DT)
    ///     DEV_FEEDBACK (구 DEVELOPER_FEEDBACK)
    ///     FEEDBACK_DT  (구 UPDT_DT)
    ///     FEEDBACK_BY  (구 UPDT_USR)
    ///     USE_YN 없음 (테이블에 해당 컬럼 없음)
    /// </summary>
    [Serializable()]
    [DesignerCategoryAttribute("code")]
    public partial class dsWorking : global::System.Data.DataSet
    {
        private E_DATADataTable tableE_DATA;

        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        public E_DATADataTable E_DATA
        {
            get { return this.tableE_DATA; }
        }

        public dsWorking()
        {
            this.InitClass();
        }

        protected dsWorking(SerializationInfo info, StreamingContext context) : base(info, context) { }

        private void InitClass()
        {
            this.DataSetName = "dsWorking";
            this.Prefix      = "";
            this.Namespace   = "http://tempuri.org/dsWorking.xsd";
            this.tableE_DATA = new E_DATADataTable();
            base.Tables.Add(this.tableE_DATA);
        }

        // GetTypedDataSetSchema 제거 (XmlSchemaProvider 미사용)

        // ====================================================================
        // E_DATADataTable
        // ====================================================================
        [Serializable()]
        [DesignerCategoryAttribute("code")]
        public partial class E_DATADataTable : TypedTableBase<E_DATARow>
        {
            // ── CUD 제어 컬럼 ──────────────────────────────────────────────
            private DataColumn columnCUD_CHAR;
            private DataColumn columnROW_NUM;
            // ── PK ────────────────────────────────────────────────────────
            private DataColumn columnLOG_SEQ;
            // ── 읽기 전용 표시 컬럼 ────────────────────────────────────────
            private DataColumn columnSESSION_ID;
            private DataColumn columnUSER_ID;
            private DataColumn columnUSER_QUERY;
            private DataColumn columnAI_RESPONSE;
            private DataColumn columnGENERATED_SQL;
            private DataColumn columnRELATED_TABLES;
            private DataColumn columnIS_ERROR;
            private DataColumn columnCREATED_DT;     // 실제 컬럼명 (구 INSRT_DT)
            // ── 편집 가능 컬럼 ─────────────────────────────────────────────
            private DataColumn columnPERF_SCORE;
            private DataColumn columnSCORE_LABEL;
            private DataColumn columnDEV_FEEDBACK;   // 실제 컬럼명 (구 DEVELOPER_FEEDBACK)
            // ── 패턴 컬럼 (편집 가능 — PA999_FEEDBACK_PATTERN) ──────────────
            private DataColumn columnCORRECT_SQL;    // 올바른 SQL (개발자 작성)
            private DataColumn columnLESSON;          // 교훈/코멘트
            // ── 감사 컬럼 (읽기 전용) ──────────────────────────────────────
            private DataColumn columnFEEDBACK_DT;    // 실제 컬럼명 (구 UPDT_DT)
            private DataColumn columnFEEDBACK_BY;    // 실제 컬럼명 (구 UPDT_USR)

            internal E_DATADataTable()
            {
                this.TableName = "E_DATA";
                this.InitClass();
            }

            // ── Column 프로퍼티 ────────────────────────────────────────────
            public DataColumn CUD_CHARColumn      { get { return this.columnCUD_CHAR; } }
            public DataColumn ROW_NUMColumn       { get { return this.columnROW_NUM; } }
            public DataColumn LOG_SEQColumn       { get { return this.columnLOG_SEQ; } }
            public DataColumn SESSION_IDColumn    { get { return this.columnSESSION_ID; } }
            public DataColumn USER_IDColumn       { get { return this.columnUSER_ID; } }
            public DataColumn USER_QUERYColumn    { get { return this.columnUSER_QUERY; } }
            public DataColumn AI_RESPONSEColumn   { get { return this.columnAI_RESPONSE; } }
            public DataColumn GENERATED_SQLColumn { get { return this.columnGENERATED_SQL; } }
            public DataColumn RELATED_TABLESColumn{ get { return this.columnRELATED_TABLES; } }
            public DataColumn IS_ERRORColumn      { get { return this.columnIS_ERROR; } }
            public DataColumn CREATED_DTColumn    { get { return this.columnCREATED_DT; } }
            public DataColumn PERF_SCOREColumn    { get { return this.columnPERF_SCORE; } }
            public DataColumn SCORE_LABELColumn   { get { return this.columnSCORE_LABEL; } }
            public DataColumn DEV_FEEDBACKColumn  { get { return this.columnDEV_FEEDBACK; } }
            public DataColumn CORRECT_SQLColumn   { get { return this.columnCORRECT_SQL; } }
            public DataColumn LESSSONColumn        { get { return this.columnLESSON; } }
            public DataColumn FEEDBACK_DTColumn   { get { return this.columnFEEDBACK_DT; } }
            public DataColumn FEEDBACK_BYColumn   { get { return this.columnFEEDBACK_BY; } }

            public int Count { get { return this.Rows.Count; } }

            public E_DATARow this[int index] { get { return (E_DATARow)this.Rows[index]; } }

            private void InitClass()
            {
                this.columnCUD_CHAR      = new DataColumn("CUD_CHAR",       typeof(string),  null, MappingType.Element);
                this.columnROW_NUM       = new DataColumn("ROW_NUM",        typeof(int),     null, MappingType.Element);
                this.columnLOG_SEQ       = new DataColumn("LOG_SEQ",        typeof(long),    null, MappingType.Element);
                this.columnSESSION_ID    = new DataColumn("SESSION_ID",     typeof(string),  null, MappingType.Element);
                this.columnUSER_ID       = new DataColumn("USER_ID",        typeof(string),  null, MappingType.Element);
                this.columnUSER_QUERY    = new DataColumn("USER_QUERY",     typeof(string),  null, MappingType.Element);
                this.columnAI_RESPONSE   = new DataColumn("AI_RESPONSE",    typeof(string),  null, MappingType.Element);
                this.columnGENERATED_SQL = new DataColumn("GENERATED_SQL",  typeof(string),  null, MappingType.Element);
                this.columnRELATED_TABLES= new DataColumn("RELATED_TABLES", typeof(string),  null, MappingType.Element);
                this.columnIS_ERROR      = new DataColumn("IS_ERROR",       typeof(bool),    null, MappingType.Element);
                this.columnCREATED_DT    = new DataColumn("CREATED_DT",     typeof(string),  null, MappingType.Element);
                this.columnPERF_SCORE    = new DataColumn("PERF_SCORE",     typeof(int),     null, MappingType.Element);
                this.columnSCORE_LABEL   = new DataColumn("SCORE_LABEL",    typeof(string),  null, MappingType.Element);
                this.columnDEV_FEEDBACK  = new DataColumn("DEV_FEEDBACK",   typeof(string),  null, MappingType.Element);
                this.columnCORRECT_SQL   = new DataColumn("CORRECT_SQL",    typeof(string),  null, MappingType.Element);
                this.columnLESSON        = new DataColumn("LESSON",          typeof(string),  null, MappingType.Element);
                this.columnFEEDBACK_DT   = new DataColumn("FEEDBACK_DT",    typeof(string),  null, MappingType.Element);
                this.columnFEEDBACK_BY   = new DataColumn("FEEDBACK_BY",    typeof(string),  null, MappingType.Element);

                base.Columns.Add(this.columnCUD_CHAR);
                base.Columns.Add(this.columnROW_NUM);
                base.Columns.Add(this.columnLOG_SEQ);
                base.Columns.Add(this.columnSESSION_ID);
                base.Columns.Add(this.columnUSER_ID);
                base.Columns.Add(this.columnUSER_QUERY);
                base.Columns.Add(this.columnAI_RESPONSE);
                base.Columns.Add(this.columnGENERATED_SQL);
                base.Columns.Add(this.columnRELATED_TABLES);
                base.Columns.Add(this.columnIS_ERROR);
                base.Columns.Add(this.columnCREATED_DT);
                base.Columns.Add(this.columnPERF_SCORE);
                base.Columns.Add(this.columnSCORE_LABEL);
                base.Columns.Add(this.columnDEV_FEEDBACK);
                base.Columns.Add(this.columnCORRECT_SQL);
                base.Columns.Add(this.columnLESSON);
                base.Columns.Add(this.columnFEEDBACK_DT);
                base.Columns.Add(this.columnFEEDBACK_BY);
            }

            protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
            {
                return new E_DATARow(builder);
            }
            protected override Type GetRowType() { return typeof(E_DATARow); }
        }

        // ====================================================================
        // E_DATARow
        // ====================================================================
        public partial class E_DATARow : DataRow
        {
            private E_DATADataTable tableE_DATA;

            internal E_DATARow(DataRowBuilder rb) : base(rb)
            {
                this.tableE_DATA = (E_DATADataTable)this.Table;
            }

            private string GetStr(DataColumn col)   { return this.IsNull(col) ? string.Empty : (string)this[col]; }
            private int    GetInt(DataColumn col)    { return this.IsNull(col) ? 0  : (int)this[col]; }
            private long   GetLong(DataColumn col)   { return this.IsNull(col) ? 0L : (long)this[col]; }
            private bool   GetBool(DataColumn col)   { return this.IsNull(col) ? false : (bool)this[col]; }

            public string CUD_CHAR
            {
                get { return GetStr(this.tableE_DATA.CUD_CHARColumn); }
                set { this[this.tableE_DATA.CUD_CHARColumn] = value; }
            }
            public int ROW_NUM
            {
                get { return GetInt(this.tableE_DATA.ROW_NUMColumn); }
                set { this[this.tableE_DATA.ROW_NUMColumn] = value; }
            }
            public long LOG_SEQ
            {
                get { return GetLong(this.tableE_DATA.LOG_SEQColumn); }
                set { this[this.tableE_DATA.LOG_SEQColumn] = value; }
            }
            public string SESSION_ID
            {
                get { return GetStr(this.tableE_DATA.SESSION_IDColumn); }
                set { this[this.tableE_DATA.SESSION_IDColumn] = value; }
            }
            public string USER_ID
            {
                get { return GetStr(this.tableE_DATA.USER_IDColumn); }
                set { this[this.tableE_DATA.USER_IDColumn] = value; }
            }
            public string USER_QUERY
            {
                get { return GetStr(this.tableE_DATA.USER_QUERYColumn); }
                set { this[this.tableE_DATA.USER_QUERYColumn] = value; }
            }
            public string AI_RESPONSE
            {
                get { return GetStr(this.tableE_DATA.AI_RESPONSEColumn); }
                set { this[this.tableE_DATA.AI_RESPONSEColumn] = value; }
            }
            public string GENERATED_SQL
            {
                get { return GetStr(this.tableE_DATA.GENERATED_SQLColumn); }
                set { this[this.tableE_DATA.GENERATED_SQLColumn] = value; }
            }
            public string RELATED_TABLES
            {
                get { return GetStr(this.tableE_DATA.RELATED_TABLESColumn); }
                set { this[this.tableE_DATA.RELATED_TABLESColumn] = value; }
            }
            public bool IS_ERROR
            {
                get { return GetBool(this.tableE_DATA.IS_ERRORColumn); }
                set { this[this.tableE_DATA.IS_ERRORColumn] = value; }
            }
            public string CREATED_DT
            {
                get { return GetStr(this.tableE_DATA.CREATED_DTColumn); }
                set { this[this.tableE_DATA.CREATED_DTColumn] = value; }
            }
            public int PERF_SCORE
            {
                get { return GetInt(this.tableE_DATA.PERF_SCOREColumn); }
                set { this[this.tableE_DATA.PERF_SCOREColumn] = value; }
            }
            public string SCORE_LABEL
            {
                get { return GetStr(this.tableE_DATA.SCORE_LABELColumn); }
                set { this[this.tableE_DATA.SCORE_LABELColumn] = value; }
            }
            public string DEV_FEEDBACK
            {
                get { return GetStr(this.tableE_DATA.DEV_FEEDBACKColumn); }
                set { this[this.tableE_DATA.DEV_FEEDBACKColumn] = value; }
            }
            public string CORRECT_SQL
            {
                get { return GetStr(this.tableE_DATA.CORRECT_SQLColumn); }
                set { this[this.tableE_DATA.CORRECT_SQLColumn] = value; }
            }
            public string LESSON
            {
                get { return GetStr(this.tableE_DATA.LESSSONColumn); }
                set { this[this.tableE_DATA.LESSSONColumn] = value; }
            }
            public string FEEDBACK_DT
            {
                get { return GetStr(this.tableE_DATA.FEEDBACK_DTColumn); }
                set { this[this.tableE_DATA.FEEDBACK_DTColumn] = value; }
            }
            public string FEEDBACK_BY
            {
                get { return GetStr(this.tableE_DATA.FEEDBACK_BYColumn); }
                set { this[this.tableE_DATA.FEEDBACK_BYColumn] = value; }
            }
        }

        public delegate void E_DATARowChangeEventHandler(object sender, E_DATARowChangeEvent e);
        public class E_DATARowChangeEvent : EventArgs
        {
            private E_DATARow eventRow;
            private DataRowAction eventAction;
            public E_DATARowChangeEvent(E_DATARow row, DataRowAction action) { this.eventRow = row; this.eventAction = action; }
            public E_DATARow Row         { get { return this.eventRow; } }
            public DataRowAction Action  { get { return this.eventAction; } }
        }
    }
}

#pragma warning restore 1591
