//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Bizentro.App.UI.PP.PA999M1_CKO087 {

    /// <summary>
    /// 챗봇 이력 조회·표시용 Working DataSet
    /// 컬럼 구성: CUD_CHAR, ROW_NUM, PLANT_CD, PLANT_NM, SEQ_NO, SESSION_ID,
    ///            QUESTION, AI_ANSWER, GENERATED_SQL, RELEVANT_TABLES,
    ///            QUERY_DT, USE_YN, REMARK
    /// </summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsWorking")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsWorking : global::System.Data.DataSet {

        private E_DATADataTable tableE_DATA;
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsWorking() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged  += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsWorking(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) :
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged  += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["E_DATA"] != null)) {
                    base.Tables.Add(new E_DATADataTable(ds.Tables["E_DATA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix      = ds.Prefix;
                this.Namespace   = ds.Namespace;
                this.Locale      = ds.Locale;
                this.CaseSensitive      = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            } else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged  += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public E_DATADataTable E_DATA {
            get { return this.tableE_DATA; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get { return this._schemaSerializationMode; }
            set { this._schemaSerializationMode = value; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get { return base.Tables; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get { return base.Relations; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsWorking cln = ((dsWorking)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables()    { return false; }
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() { return false; }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["E_DATA"] != null)) {
                    base.Tables.Add(new E_DATADataTable(ds.Tables["E_DATA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix      = ds.Prefix;
                this.Namespace   = ds.Namespace;
                this.Locale      = ds.Locale;
                this.CaseSensitive      = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            } else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() { this.InitVars(true); }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableE_DATA = ((E_DATADataTable)(base.Tables["E_DATA"]));
            if ((initTable == true)) {
                if ((this.tableE_DATA != null)) { this.tableE_DATA.InitVars(); }
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName        = "dsWorking";
            this.Prefix             = "";
            this.Namespace          = "http://tempuri.org/dsWorking.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableE_DATA = new E_DATADataTable();
            base.Tables.Add(this.tableE_DATA);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeE_DATA() { return false; }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) { this.InitVars(); }
        }

        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsWorking ds = new dsWorking();
            global::System.Xml.Schema.XmlSchemaComplexType type     = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence    sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
            any1.Namespace       = "http://www.w3.org/2001/XMLSchema";
            any1.MinOccurs       = new decimal(0);
            any1.MaxOccurs       = decimal.MaxValue;
            any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any1);
            global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
            any2.Namespace       = "urn:schemas-microsoft-com:xml-diffgram-v1";
            any2.MinOccurs       = new decimal(1);
            any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any2);
            global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute1.Name       = "namespace";
            attribute1.FixedValue = ds.Namespace;
            type.Attributes.Add(attribute1);
            global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute2.Name       = "tableTypeName";
            attribute2.FixedValue = "E_DATADataTable";
            type.Attributes.Add(attribute2);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) && (s1.ReadByte() == s2.ReadByte())); ) { ; }
                            if ((s1.Position == s1.Length)) { return type; }
                        }
                    }
                } finally {
                    if ((s1 != null)) s1.Close();
                    if ((s2 != null)) s2.Close();
                }
            }
            xs.Add(dsSchema);
            return type;
        }

        // ──────────────────────────────────────────────────────────────────
        // E_DATADataTable
        // ──────────────────────────────────────────────────────────────────
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class E_DATADataTable : global::System.Data.TypedTableBase<E_DATARow> {

            private global::System.Data.DataColumn columnCUD_CHAR;
            private global::System.Data.DataColumn columnROW_NUM;
            private global::System.Data.DataColumn columnPLANT_CD;
            private global::System.Data.DataColumn columnPLANT_NM;
            private global::System.Data.DataColumn columnSEQ_NO;
            private global::System.Data.DataColumn columnSESSION_ID;
            private global::System.Data.DataColumn columnQUESTION;
            private global::System.Data.DataColumn columnAI_ANSWER;
            private global::System.Data.DataColumn columnGENERATED_SQL;
            private global::System.Data.DataColumn columnRELEVANT_TABLES;
            private global::System.Data.DataColumn columnQUERY_DT;
            private global::System.Data.DataColumn columnUSE_YN;
            private global::System.Data.DataColumn columnREMARK;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public E_DATADataTable() {
                this.TableName = "E_DATA";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal E_DATADataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) { this.CaseSensitive = table.CaseSensitive; }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) { this.Locale = table.Locale; }
                if ((table.Namespace != table.DataSet.Namespace)) { this.Namespace = table.Namespace; }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected E_DATADataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) :
                    base(info, context) { this.InitVars(); }

            // ── Column properties ─────────────────────────────────────────
            public global::System.Data.DataColumn CUD_CHARColumn        { get { return this.columnCUD_CHAR; } }
            public global::System.Data.DataColumn ROW_NUMColumn         { get { return this.columnROW_NUM; } }
            public global::System.Data.DataColumn PLANT_CDColumn        { get { return this.columnPLANT_CD; } }
            public global::System.Data.DataColumn PLANT_NMColumn        { get { return this.columnPLANT_NM; } }
            public global::System.Data.DataColumn SEQ_NOColumn          { get { return this.columnSEQ_NO; } }
            public global::System.Data.DataColumn SESSION_IDColumn      { get { return this.columnSESSION_ID; } }
            public global::System.Data.DataColumn QUESTIONColumn        { get { return this.columnQUESTION; } }
            public global::System.Data.DataColumn AI_ANSWERColumn       { get { return this.columnAI_ANSWER; } }
            public global::System.Data.DataColumn GENERATED_SQLColumn   { get { return this.columnGENERATED_SQL; } }
            public global::System.Data.DataColumn RELEVANT_TABLESColumn { get { return this.columnRELEVANT_TABLES; } }
            public global::System.Data.DataColumn QUERY_DTColumn        { get { return this.columnQUERY_DT; } }
            public global::System.Data.DataColumn USE_YNColumn          { get { return this.columnUSE_YN; } }
            public global::System.Data.DataColumn REMARKColumn          { get { return this.columnREMARK; } }

            [global::System.ComponentModel.Browsable(false)]
            public int Count { get { return this.Rows.Count; } }

            public E_DATARow this[int index] { get { return ((E_DATARow)(this.Rows[index])); } }

            public event E_DATARowChangeEventHandler E_DATARowChanging;
            public event E_DATARowChangeEventHandler E_DATARowChanged;
            public event E_DATARowChangeEventHandler E_DATARowDeleting;
            public event E_DATARowChangeEventHandler E_DATARowDeleted;

            public void AddE_DATARow(E_DATARow row) { this.Rows.Add(row); }

            public E_DATARow AddE_DATARow(
                string CUD_CHAR, int ROW_NUM,
                string PLANT_CD, string PLANT_NM,
                int    SEQ_NO,   string SESSION_ID,
                string QUESTION, string AI_ANSWER,
                string GENERATED_SQL, string RELEVANT_TABLES,
                string QUERY_DT,
                string USE_YN,   string REMARK)
            {
                E_DATARow rowE_DATARow = ((E_DATARow)(this.NewRow()));
                rowE_DATARow.ItemArray = new object[] {
                    CUD_CHAR, ROW_NUM,
                    PLANT_CD, PLANT_NM,
                    SEQ_NO,   SESSION_ID,
                    QUESTION, AI_ANSWER,
                    GENERATED_SQL, RELEVANT_TABLES,
                    QUERY_DT,
                    USE_YN, REMARK };
                this.Rows.Add(rowE_DATARow);
                return rowE_DATARow;
            }

            public override global::System.Data.DataTable Clone() {
                E_DATADataTable cln = ((E_DATADataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }

            protected override global::System.Data.DataTable CreateInstance() { return new E_DATADataTable(); }

            internal void InitVars() {
                this.columnCUD_CHAR        = base.Columns["CUD_CHAR"];
                this.columnROW_NUM         = base.Columns["ROW_NUM"];
                this.columnPLANT_CD        = base.Columns["PLANT_CD"];
                this.columnPLANT_NM        = base.Columns["PLANT_NM"];
                this.columnSEQ_NO          = base.Columns["SEQ_NO"];
                this.columnSESSION_ID      = base.Columns["SESSION_ID"];
                this.columnQUESTION        = base.Columns["QUESTION"];
                this.columnAI_ANSWER       = base.Columns["AI_ANSWER"];
                this.columnGENERATED_SQL   = base.Columns["GENERATED_SQL"];
                this.columnRELEVANT_TABLES = base.Columns["RELEVANT_TABLES"];
                this.columnQUERY_DT        = base.Columns["QUERY_DT"];
                this.columnUSE_YN          = base.Columns["USE_YN"];
                this.columnREMARK          = base.Columns["REMARK"];
            }

            private void InitClass() {
                this.columnCUD_CHAR        = new global::System.Data.DataColumn("CUD_CHAR",        typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnCUD_CHAR);
                this.columnROW_NUM         = new global::System.Data.DataColumn("ROW_NUM",         typeof(int),    null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnROW_NUM);
                this.columnPLANT_CD        = new global::System.Data.DataColumn("PLANT_CD",        typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnPLANT_CD);
                this.columnPLANT_NM        = new global::System.Data.DataColumn("PLANT_NM",        typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnPLANT_NM);
                this.columnSEQ_NO          = new global::System.Data.DataColumn("SEQ_NO",          typeof(int),    null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnSEQ_NO);
                this.columnSESSION_ID      = new global::System.Data.DataColumn("SESSION_ID",      typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnSESSION_ID);
                this.columnQUESTION        = new global::System.Data.DataColumn("QUESTION",        typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnQUESTION);
                this.columnAI_ANSWER       = new global::System.Data.DataColumn("AI_ANSWER",       typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnAI_ANSWER);
                this.columnGENERATED_SQL   = new global::System.Data.DataColumn("GENERATED_SQL",   typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnGENERATED_SQL);
                this.columnRELEVANT_TABLES = new global::System.Data.DataColumn("RELEVANT_TABLES", typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnRELEVANT_TABLES);
                this.columnQUERY_DT        = new global::System.Data.DataColumn("QUERY_DT",        typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnQUERY_DT);
                this.columnUSE_YN          = new global::System.Data.DataColumn("USE_YN",          typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnUSE_YN);
                this.columnREMARK          = new global::System.Data.DataColumn("REMARK",          typeof(string), null, global::System.Data.MappingType.Element); base.Columns.Add(this.columnREMARK);
            }

            public E_DATARow NewE_DATARow() { return ((E_DATARow)(this.NewRow())); }

            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) { return new E_DATARow(builder); }

            protected override global::System.Type GetRowType() { return typeof(E_DATARow); }

            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.E_DATARowChanged != null)) this.E_DATARowChanged(this, new E_DATARowChangeEvent(((E_DATARow)(e.Row)), e.Action));
            }
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.E_DATARowChanging != null)) this.E_DATARowChanging(this, new E_DATARowChangeEvent(((E_DATARow)(e.Row)), e.Action));
            }
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.E_DATARowDeleted != null)) this.E_DATARowDeleted(this, new E_DATARowChangeEvent(((E_DATARow)(e.Row)), e.Action));
            }
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.E_DATARowDeleting != null)) this.E_DATARowDeleting(this, new E_DATARowChangeEvent(((E_DATARow)(e.Row)), e.Action));
            }

            public void RemoveE_DATARow(E_DATARow row) { this.Rows.Remove(row); }

            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsWorking ds = new dsWorking();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema"; any1.MinOccurs = new decimal(0); any1.MaxOccurs = decimal.MaxValue; any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax; sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"; any2.MinOccurs = new decimal(1); any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax; sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute(); attribute1.Name = "namespace"; attribute1.FixedValue = ds.Namespace; type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute(); attribute2.Name = "tableTypeName"; attribute2.FixedValue = "E_DATADataTable"; type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                xs.Add(dsSchema);
                return type;
            }
        }

        // ──────────────────────────────────────────────────────────────────
        // E_DATARow
        // ──────────────────────────────────────────────────────────────────
        public partial class E_DATARow : global::System.Data.DataRow {
            private E_DATADataTable tableE_DATA;

            internal E_DATARow(global::System.Data.DataRowBuilder rb) : base(rb) {
                this.tableE_DATA = ((E_DATADataTable)(this.Table));
            }

            public string CUD_CHAR        { get { return ((string)(this[this.tableE_DATA.CUD_CHARColumn])); }        set { this[this.tableE_DATA.CUD_CHARColumn] = value; } }
            public int    ROW_NUM         { get { return ((int)(this[this.tableE_DATA.ROW_NUMColumn])); }            set { this[this.tableE_DATA.ROW_NUMColumn] = value; } }
            public string PLANT_CD        { get { return ((string)(this[this.tableE_DATA.PLANT_CDColumn])); }        set { this[this.tableE_DATA.PLANT_CDColumn] = value; } }
            public string PLANT_NM        { get { return ((string)(this[this.tableE_DATA.PLANT_NMColumn])); }        set { this[this.tableE_DATA.PLANT_NMColumn] = value; } }
            public int    SEQ_NO          { get { return ((int)(this[this.tableE_DATA.SEQ_NOColumn])); }             set { this[this.tableE_DATA.SEQ_NOColumn] = value; } }
            public string SESSION_ID      { get { return ((string)(this[this.tableE_DATA.SESSION_IDColumn])); }      set { this[this.tableE_DATA.SESSION_IDColumn] = value; } }
            public string QUESTION        { get { return ((string)(this[this.tableE_DATA.QUESTIONColumn])); }        set { this[this.tableE_DATA.QUESTIONColumn] = value; } }
            public string AI_ANSWER       { get { return ((string)(this[this.tableE_DATA.AI_ANSWERColumn])); }       set { this[this.tableE_DATA.AI_ANSWERColumn] = value; } }
            public string GENERATED_SQL   { get { return ((string)(this[this.tableE_DATA.GENERATED_SQLColumn])); }   set { this[this.tableE_DATA.GENERATED_SQLColumn] = value; } }
            public string RELEVANT_TABLES { get { return ((string)(this[this.tableE_DATA.RELEVANT_TABLESColumn])); } set { this[this.tableE_DATA.RELEVANT_TABLESColumn] = value; } }
            public string QUERY_DT        { get { return ((string)(this[this.tableE_DATA.QUERY_DTColumn])); }        set { this[this.tableE_DATA.QUERY_DTColumn] = value; } }
            public string USE_YN          { get { return ((string)(this[this.tableE_DATA.USE_YNColumn])); }          set { this[this.tableE_DATA.USE_YNColumn] = value; } }
            public string REMARK          { get { return ((string)(this[this.tableE_DATA.REMARKColumn])); }          set { this[this.tableE_DATA.REMARKColumn] = value; } }
        }

        // ──────────────────────────────────────────────────────────────────
        // E_DATARowChangeEvent
        // ──────────────────────────────────────────────────────────────────
        public class E_DATARowChangeEvent : global::System.EventArgs {
            private E_DATARow eventRow;
            private global::System.Data.DataRowAction eventAction;
            public E_DATARowChangeEvent(E_DATARow row, global::System.Data.DataRowAction action) { this.eventRow = row; this.eventAction = action; }
            public E_DATARow Row    { get { return this.eventRow; } }
            public global::System.Data.DataRowAction Action { get { return this.eventAction; } }
        }

        public delegate void E_DATARowChangeEventHandler(object sender, E_DATARowChangeEvent e);
    }
}
